# Generated by Django 4.2.3 on 2023-08-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Employee_details',
            new_name='Employee_detail',
        ),
    ]
