# Generated by Django 4.2.3 on 2023-08-07 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_project_rename_employee_details_employee_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('percentage', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employee_detail')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.project')),
            ],
            options={
                'unique_together': {('emp_id', 'project_id')},
            },
        ),
    ]
