# Generated by Django 4.2.3 on 2023-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_workingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtime',
            name='time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
