# Generated by Django 4.2.3 on 2023-08-08 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
