# Generated by Django 4.2.3 on 2023-08-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
