# Generated by Django 4.2.3 on 2023-08-10 10:29

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.FileField(max_length=200, upload_to=login.models.generate_unique_filename)),
                ('report', models.FileField(max_length=200, upload_to=login.models.generate_unique_filename)),
            ],
        ),
    ]
