# Generated by Django 4.2.3 on 2023-08-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_employeemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
