# Generated by Django 4.2.3 on 2023-08-12 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_employee_detail_last_inserted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_prct_inserted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
